version: "3"
services:
  sonarqube:
    image: sonarqube
    depends_on:
      - db
    networks:
      - sonarnet
    container_name: sonarqube
    restart: always
    environment:
      - SONARQUBE_JDBC_USERNAME=postgres
      - SONARQUBE_JDBC_PASSWORD=sonartest123
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    container_name: database-postgresql
    restart: always
    environment:
      #- POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sonartest123
      #- POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - sonarqube_db:/var/lib/postgresql10
      - postgresql_data:/var/lib/postgresql10/data

networks:
  sonarnet:
    driver: bridge

volumes:
  postgresql_data:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_db:
  sonarqube_extensions:
